// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

#ifndef PROTOBUF_INCLUDED_Message_2eproto
#define PROTOBUF_INCLUDED_Message_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Message_2eproto 

namespace protobuf_Message_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Message_2eproto
namespace MP {
class TcpMessage;
class TcpMessageDefaultTypeInternal;
extern TcpMessageDefaultTypeInternal _TcpMessage_default_instance_;
}  // namespace MP
namespace google {
namespace protobuf {
template<> ::MP::TcpMessage* Arena::CreateMaybeMessage<::MP::TcpMessage>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace MP {

// ===================================================================

class TcpMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MP.TcpMessage) */ {
 public:
  TcpMessage();
  virtual ~TcpMessage();

  TcpMessage(const TcpMessage& from);

  inline TcpMessage& operator=(const TcpMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TcpMessage(TcpMessage&& from) noexcept
    : TcpMessage() {
    *this = ::std::move(from);
  }

  inline TcpMessage& operator=(TcpMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TcpMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TcpMessage* internal_default_instance() {
    return reinterpret_cast<const TcpMessage*>(
               &_TcpMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TcpMessage* other);
  friend void swap(TcpMessage& a, TcpMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TcpMessage* New() const final {
    return CreateMaybeMessage<TcpMessage>(NULL);
  }

  TcpMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TcpMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TcpMessage& from);
  void MergeFrom(const TcpMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TcpMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string msg = 2;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // int32 packetNum = 1;
  void clear_packetnum();
  static const int kPacketNumFieldNumber = 1;
  ::google::protobuf::int32 packetnum() const;
  void set_packetnum(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MP.TcpMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 packetnum_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Message_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TcpMessage

// int32 packetNum = 1;
inline void TcpMessage::clear_packetnum() {
  packetnum_ = 0;
}
inline ::google::protobuf::int32 TcpMessage::packetnum() const {
  // @@protoc_insertion_point(field_get:MP.TcpMessage.packetNum)
  return packetnum_;
}
inline void TcpMessage::set_packetnum(::google::protobuf::int32 value) {
  
  packetnum_ = value;
  // @@protoc_insertion_point(field_set:MP.TcpMessage.packetNum)
}

// string msg = 2;
inline void TcpMessage::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TcpMessage::msg() const {
  // @@protoc_insertion_point(field_get:MP.TcpMessage.msg)
  return msg_.GetNoArena();
}
inline void TcpMessage::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MP.TcpMessage.msg)
}
#if LANG_CXX11
inline void TcpMessage::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MP.TcpMessage.msg)
}
#endif
inline void TcpMessage::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MP.TcpMessage.msg)
}
inline void TcpMessage::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MP.TcpMessage.msg)
}
inline ::std::string* TcpMessage::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:MP.TcpMessage.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TcpMessage::release_msg() {
  // @@protoc_insertion_point(field_release:MP.TcpMessage.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TcpMessage::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:MP.TcpMessage.msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace MP

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Message_2eproto
